export const INFO = {
  WEBSITE: "nkvi.xyz",
  REF: "https://www.nkvi.xyz",
  PRODUCT: "NetMe",
  ABOUT_US: "https://www.nkvi.xyz",
  LICENSE: "https://www.nkvi.xyz",
  CHINA_NAME: "阮轲伟",
  NAME: `Kha-Vi Nguyen (阮轲伟)`,
  EMAIL: "nkvi.dev@gmail.com",
  CC_EMAIL: "nguyenkhavi01032001@gmail.com",
  NICKNAME: "nkvi",
  LINKED_IN: "https://www.linkedin.com/in/nguyenkhavi/",
  INSTAGRAM: "https://www.instagram.com/khavi.ng_/",
  FACEBOOK: "https://www.facebook.com/profile.php?id=100009911809403",
  TWITTER: "https://twitter.com/vi_nguyen2001",
  GITHUB: "https://github.com/nguyenkhavi",
  TERMS_CONS: "https://www.nkvi.xyz",
  PRIVACY_POLICY: "https://www.nkvi.xyz",
  CONTACT_US: "https://www.nkvi.xyz",
};
